name: CI Pipeline for kubedash

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Go environment
      uses: actions/setup-go@v4
      with:
        go-version: 1.21  # Ensure to match your Go version

    - name: Install dependencies
      run: go mod tidy

   

    - name: Run unit tests
      run: go test ./... -v -cover

    - name: Build CLI tool
      run: |
        go build -o dist/kubedash main.go

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kubedash-binary
        path: dist/
