name: Release Pipeline for kubedash

on:
  push:
   
    tags:
      - "v*.*.*" 

jobs:
  
  release:
        runs-on: ubuntu-latest 
        permissions:
            contents: write 
        steps:
        - name: Check out the code
          uses: actions/checkout@v3
    
        - name: Set up Go
          uses: actions/setup-go@v4
          with:
              go-version: 1.21
        - name: Run Goreleaser
          uses: goreleaser/goreleaser-action@v4
          with:
            version: '~> v2'
            args: release --clean
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        